### PR TITLE
Add cloud function code for uploading files from url to gcs

### PR DESCRIPTION
**Pull request by jenniebrown**
This is a rough copy of Brian's demo cloud function code with error handling that can be generically used for pulling data from a url #14

### CODE REVIEW

**Review by mayaspivak — APPROVED** [review]
Not blocking this change, but is there a way to get a last updated timestamp for the data? That would be useful to check before copying it over every time if it hasn't changed.

**Review by mayaspivak — CHANGES_REQUESTED** [review]
Actually, maybe we should put the python file under a directory named something like "ingestion" so by functionality instead of by compute mechanism.

**Comment by jenniebrown** [comment]
> Actually, maybe we should put the python file under a directory named something like "ingestion" so by functionality instead of by compute mechanism.

done

**Review by mayaspivak — APPROVED** [review]

**Comment by jenniebrown** [comment]
> Not blocking this change, but is there a way to get a last updated timestamp for the data? That would be useful to check before copying it over every time if it hasn't changed.

Yeah, we will definitely want that. The USDA site has an html table with the last updated date but I'm looking to see if it's possible to do that in a generic way.

**Pull request merged**
